export { default as Navbar } from "./Navbar/Navbar";
export { default as DropDown } from "./DropDown/DropDown";
export { default as BgAnimation } from "./BgAnimation/BgAnimation";
export { default as InfoSection } from "./InfoSection/InfoSection";
export { default as Technologies } from "./Technologies/Technologies";
export { default as About } from "./About/About";
export { default as Accomplishments } from "./Accomplishments/Accomplishments";
export { default as Footer } from "./Footer/Footer";
export { default as Projects } from "./Projects/Projects";
